# This is a basic workflow to help you get started with Actions

name: Data Getter

# Controls when the workflow will run
on:
  schedule:
    - cron: '4 2 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v14.17.2

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      # Runs a set of commands using the runners shell
      - name: Fetch and interpolate the data
        env:
          NOMICS_API_KEY: ${{ secrets.NOMICS_API_KEY }}
          RIVET_API_KEY: ${{ secrets.RIVET_API_KEY }}
        run: |
          mkdir -p data
          curl "https://api.nomics.com/v1/currencies/ticker?key=${NOMICS_API_KEY}&ids=ETC&interval=1d,30d&convert=USD&per-page=100&page=1" > data/exchange_rates.json
          echo -n "export const ExchangeData =" > src/scripts/data.js
          cat data/exchange_rates.json >> src/scripts/data.js
          echo -n ";" >> src/scripts/data.js
          
          curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "eth_getBlockByNumber", "params": ["latest", false]}' https://${RIVET_API_KEY}.etc.rpc.rivet.cloud > data/rivet_etc_latest_block.json
          curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "eth_getBlockByNumber", "params": ["latest", false]}' https://${RIVET_API_KEY}.eth.rpc.rivet.cloud > data/rivet_eth_latest_block.json
          
          echo -n "export const ETC_Latest_Block =" > src/scripts/chaindata.js
          cat data/rivet_etc_latest_block.json >> src/scripts/chaindata.js
          echo -n ";" >> src/scripts/chaindata.js
          
          echo -n "export const ETH_Latest_Block =" >> src/scripts/chaindata.js
          cat data/rivet_eth_latest_block.json >> src/scripts/chaindata.js
          echo -n ";" >> src/scripts/chaindata.js

      - run: yarn
      - run: yarn build

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '.'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Robo Meows

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: b5c6@protonmail.com

          # Additional arguments for the git commit command. The --message argument is already set by the message input.
          # Default: ''
          commit: --signoff

          # The name of the custom committer you want to use, if different from the author of the commit.
          # Default: the name of the author (set with either author_name or default_author)
          committer_name: Robo Meows

          # The email of the custom committer you want to use, if different from the author of the commit.
          # Default: the email of the author (set with either author_email or default_author)
          committer_email: b5c6@protonmail.com

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
          # Default: '.'
          cwd: '.'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'auto-committed exchange rate data'

          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
#           new_branch: gh-pages

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: ignore

          # Arguments for the git pull command. By default, the action does not pull.
          # Default: ''
#           pull: '--rebase --autostash ...'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
#           remove: './dir/old_file.js'

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
#           tag: 'v1.0.0 --force'

          # Arguments for the git push --tags command (any additional argument will be added after --tags)
          # Default: ''
#           tag_push: '--force'

      - uses: actions/upload-pages-artifact@main
        with:
          path: public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
